In [141]:
import pandas as pd
import numpy as np

from sklearn.cluster import KMeans, AgglomerativeClustering

from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.metrics import classification_report

In [99]:
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/00488/Live_20210128.csv")

In [100]:
df.shape

(7050, 16)

In [101]:
df.isna().sum()

status_id              0
status_type            0
status_published       0
num_reactions          0
num_comments           0
num_shares             0
num_likes              0
num_loves              0
num_wows               0
num_hahas              0
num_sads               0
num_angrys             0
Column1             7050
Column2             7050
Column3             7050
Column4             7050
dtype: int64

4 Features contains null values

In [102]:
df.dropna(axis=1,inplace=True)

In [103]:
df['status_type'].value_counts()

photo     4288
video     2334
status     365
link        63
Name: status_type, dtype: int64

In [104]:
X=df
y=X.pop('status_type')

In [105]:
X.head()

status_id status_published  num_reactions  num_comments  num_shares  \
0          1   4/22/2018 6:00            529           512         262   
1          2  4/21/2018 22:45            150             0           0   
2          3   4/21/2018 6:17            227           236          57   
3          4   4/21/2018 2:29            111             0           0   
4          5   4/18/2018 3:22            213             0           0   

   num_likes  num_loves  num_wows  num_hahas  num_sads  num_angrys  
0        432         92         3          1         1           0  
1        150          0         0          0         0           0  
2        204         21         1          1         0           0  
3        111          0         0          0         0           0  
4        204          9         0          0         0           0

In [106]:
# dropping the features 
cols = ['status_id', 'status_published']
X.drop(cols,axis=1,inplace=True)

In [107]:
# tranfroming target variable with label encoder

encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [108]:
y

array([3, 1, 3, ..., 1, 1, 1])

In [109]:
# sclaing features with standard scaler

scaler = StandardScaler()
X = scaler.fit_transform(X)

In [110]:
X

array([[ 0.64610394,  0.32335035,  1.6868788 , ...,  0.07671305,
         0.47357035, -0.15574803],
       [-0.17319166, -0.25220622, -0.3041444 , ..., -0.17600986,
        -0.152587  , -0.15574803],
       [-0.00673846,  0.01308938,  0.12901714, ...,  0.07671305,
        -0.152587  , -0.15574803],
       ...,
       [-0.49312768, -0.25220622, -0.3041444 , ..., -0.17600986,
        -0.152587  , -0.15574803],
       [ 0.26131603, -0.23871662, -0.13695924, ..., -0.17600986,
        -0.152587  , -0.15574803],
       [-0.46070173, -0.25220622, -0.3041444 , ..., -0.17600986,
        -0.152587  , -0.15574803]])

## KMeans Clustering

In [126]:
# KMeans at k=2
kmeans = KMeans(n_clusters=2, random_state=10)
kmeans.fit(X, y)

KMeans(n_clusters=2, random_state=10)

In [127]:
kmeans.inertia_

48278.09824220544

In [128]:
kmeans.labels_

array([0, 0, 0, ..., 0, 0, 0], dtype=int32)

In [129]:
# KMeans at k=4
kmeans4 = KMeans(n_clusters=4, random_state=10)
kmeans4.fit(X, y)

KMeans(n_clusters=4, random_state=10)

In [130]:
kmeans4.labels_

array([1, 1, 1, ..., 1, 1, 1], dtype=int32)

In [131]:
predictions = kmeans4.labels_
np.sum(predictions==y)

4421

## Agglomerative Clustering

In [135]:
agg = AgglomerativeClustering(n_clusters=4,
                              affinity='euclidean',
                              linkage ='ward')

In [136]:
agg.fit(X,y)

AgglomerativeClustering(n_clusters=4)

In [138]:
agg.labels_

array([3, 3, 3, ..., 3, 3, 3])

In [139]:
agg.n_leaves_

7050

In [143]:
print(classification_report(agg.labels_,y))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       321
           1       0.00      0.04      0.00        27
           2       0.21      0.20      0.20       393
           3       0.83      0.31      0.45      6309

    accuracy                           0.28      7050
   macro avg       0.26      0.13      0.16      7050
weighted avg       0.75      0.28      0.41      7050

