In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv('data.csv')

In [8]:
df.head()

Feature-1  Feature-2  Feature-3  Feature-4  Feature-5  Feature-6  \
0     -1.580     1.0500      1.060     -0.440      0.451    -0.0348   
1     -0.832    -0.8660     -1.340      0.138      1.180     0.7330   
2     -0.237     2.0900     -3.930      0.296      0.352    -0.5010   
3     -1.170    -1.1300     -1.090      1.120      0.312     0.1830   
4      0.260    -0.0273      0.925     -1.150     -1.390     0.0251   

   Feature-7  Feature-8  Feature-9  Feature-10  Target  
0      0.643     0.2650      0.268      -0.851    84.7  
1     -1.410     0.1350     -0.088      -1.550  -211.0  
2      0.961    -0.0287      1.820       0.938   -96.9  
3      0.448    -0.8190     -1.010      -1.080  -152.0  
4      0.627     0.0950     -0.280      -0.848   -57.7

In [9]:
y = df.pop('Target')
X = df

In [10]:
X.head()

Feature-1  Feature-2  Feature-3  Feature-4  Feature-5  Feature-6  \
0     -1.580     1.0500      1.060     -0.440      0.451    -0.0348   
1     -0.832    -0.8660     -1.340      0.138      1.180     0.7330   
2     -0.237     2.0900     -3.930      0.296      0.352    -0.5010   
3     -1.170    -1.1300     -1.090      1.120      0.312     0.1830   
4      0.260    -0.0273      0.925     -1.150     -1.390     0.0251   

   Feature-7  Feature-8  Feature-9  Feature-10  
0      0.643     0.2650      0.268      -0.851  
1     -1.410     0.1350     -0.088      -1.550  
2      0.961    -0.0287      1.820       0.938  
3      0.448    -0.8190     -1.010      -1.080  
4      0.627     0.0950     -0.280      -0.848

In [16]:
X.shape,y.shape

((90000, 10), (90000,))

In [12]:
X_array = X.to_numpy()
y_array = y.to_numpy()

In [27]:
X_ = X_array.reshape(-1,90,10)
y_ = y_array.reshape(-1,90,1)

In [28]:
X_.shape,y_.shape

((1000, 90, 10), (1000, 90, 1))

In [21]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X_,y_,test_size=0.3,random_state=10)

In [32]:
X_train.shape,y_train.shape,X_test.shape,y_test.shape

((700, 90, 10), (700, 90, 1), (300, 90, 10), (300, 90, 1))

In [29]:
from sklearn.linear_model import SGDRegressor

regressor = SGDRegressor(random_state=10)

In [ ]:
#selecting data in batches
for i in range(X_train.shape[0]):
  X_batch, y_batch = X_train[i],y_train[i]
  #partially fitting data in batches
  regressor.partial_fit(X_batch,y_batch)

In [31]:
regressor.intercept_

array([-0.01306907])

In [35]:
regressor.coef_

array([51.3105364 , 22.28887652, 81.2555404 , 53.20103481, 76.45558585,
       71.4819568 , 93.45919069, 51.93738032, 30.03948184, 40.9838626 ])

In [38]:
from sklearn.metrics import r2_score

y_preds = []
for i in range(X_test.shape[0]):
  y_pred = regressor.predict(X_test[i])
  y_preds.append(y_pred)

In [44]:
np.asarray(y_preds).shape, y_test.shape

((300, 90), (300, 90, 1))

In [53]:
y_test_1 = y_test.reshape(-1)
y_pred_1 = np.asarray(y_preds).reshape(-1)

In [55]:
#r2score
r2 = r2_score(y_test_1,y_pred_1)
r2

0.9999917482397119

In [57]:
regressor.coef_

array([51.3105364 , 22.28887652, 81.2555404 , 53.20103481, 76.45558585,
       71.4819568 , 93.45919069, 51.93738032, 30.03948184, 40.9838626 ])

In [59]:
from sklearn.datasets import load_iris

In [72]:
X,y = load_iris(return_X_y=True)

In [73]:
from sklearn.preprocessing import Normalizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline

In [74]:
X_train, X_test, y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=10)

In [79]:
scaler = Normalizer()
scaler.fit(X_train)

Normalizer()

In [80]:
X_train_trans =  scaler.transform(X_train)
X_test_trans = scaler.transform(X_test)

In [82]:
from sklearn.metrics import accuracy_score

for i in range (2,5):
   knn = KNeighborsClassifier(i)
   knn.fit(X_train_trans,y_train)
   y_pred = knn.predict(X_test_trans)
   print(f'For k={i}, accuracy is {(accuracy_score(y_test,y_pred)):.3f}')

For k=2, accuracy is 0.967
For k=3, accuracy is 0.967
For k=4, accuracy is 0.967


In [98]:
# weighted f1 score 
from sklearn.metrics import f1_score

knn2 = KNeighborsClassifier(3)
knn2.fit(X_train_trans,y_train)
y_pred2 = knn2.predict(X_test_trans)
f1=f1_score(y_test,y_pred2, average='weighted')
print(f'weighted f1 score for k=3 is {f1:.3f}')

weighted f1 score for k=3 is 0.967
